### PR TITLE
zathura: man pages updated

### PR DESCRIPTION
**Pull request by Vouivre**
## Note

The man pages had to be updated. So no recompilation is needed. I have in mind in that case
the version should not be changed. But, if I understand right, if somebody has already installed `zathura`,
the man pages won't be updated. Can you confirm ? 

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
>  if somebody has already installed zathura, the man pages won't be updated

This is correct

**Comment by Vouivre** [comment]
The updated man page contains a new option to copy an url the the clipboard (shortcut `c`).  [In this case](https://www.reddit.com/r/kisslinux/comments/ortakk/firefox_on_wayland_command_line_to_open_a_new_tab/
), it can be very useful.

Between a new compilation which is not so long and this intersting option, I think it's better to recompile
`zathura` and update the man pages.

I have also updated the version of `zathura`.

**Comment by aabacchus** [comment]
@Vouivre please update the checksums accordingly.

**Comment by Vouivre** [comment]
I thought: easy change.... and I forgot the checksums.... thanks!
 https://github.com/kiss-community/community/pull/741

**Pull request merged**
