### PR TITLE
elinks: new package at 0.15

### PR DESCRIPTION
**Pull request by TAAPArthur**
Please fill out the template.

Read: https://k1sslinux.org/wiki/kiss/style-guide

Please include the manifest for version bumps and new packages.

---

## Description of package
Maintained version of the original elinks

## Installed manifest of package

(`kiss manifest <pkg>`)

```
/var/db/kiss/installed/elinks/version
/var/db/kiss/installed/elinks/sources
/var/db/kiss/installed/elinks/manifest
/var/db/kiss/installed/elinks/depends
/var/db/kiss/installed/elinks/checksums
/var/db/kiss/installed/elinks/build
/var/db/kiss/installed/elinks/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man5/elinkskeys.5
/usr/share/man/man5/elinks.conf.5
/usr/share/man/man5/
/usr/share/man/man1/elinks.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/bin/elinks
/usr/bin/
/usr/

```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

## Existing package

- [ ] I am the maintainer of this package.

### CODE REVIEW

**Comment by Mederim** [comment]
@dilyn-corner elinks is in wrong path, is out of community dir

**Comment by TAAPArthur** [comment]
Ops. I pushed a fix to this user branch, but should I open another PR?

**Comment by Mederim** [comment]
Better idea

**Comment by dilyn-corner** [comment]
The one thing I never check >.<

Open a new PR pls

**Pull request merged**
