### PR TITLE
libcap: bump to  2.51

### PR DESCRIPTION
**Pull request by mmatongo**
## Existing package

- [Y] I am the maintainer of this package.

### CODE REVIEW

**Comment by mmatongo** [comment]
This is possibly scuffed but it does build and nothing seems to be missing.
If there's a patch or something that fixes the failing build please make mention and I'll get rid of the `sed`.

**Comment by dilyn-corner** [comment]
So your `sed` stops the execution of some `bash` script which... diffs a collection of text files documenting usage with a header file. That header file is just... Documentation that contains explanations of usage/features/whatever.

I think we can do without it. If somebody asks why xyz explanation isn't included with `capsh`, we will have to remember that this is why.

**Comment by mmatongo** [comment]
> So your `sed` stops the execution of some `bash` script which... diffs a collection of text files documenting usage with a header file. That header file is just... Documentation that contains explanations of usage/features/whatever.
> 
> 
> 
> I think we can do without it. If somebody asks why xyz explanation isn't included with `capsh`, we will have to remember that this is why.


Should be easy enough to remember.

**Comment by mmatongo** [comment]
I'll update the rest of my packages as soon as my power is restored

**Pull request merged**
