### PR TITLE
fix lints

### PR DESCRIPTION
**Pull request by jedahan**
Lint on PRs, and this fixes most of them. Would appreciate any review @dilyn-corner

### CODE REVIEW

**Comment by dilyn-corner** [comment]
`cmus` and `libmad` have had their version files deleted...?

I'll take a closer look, but I think you're basically there with this :)

**Comment by jedahan** [comment]
Shouldn’t be deleted, just change permissions so there’s no file diff, just metadata diff

**Comment by dilyn-corner** [comment]
Can we rebase/rerun this? Then we can tag everyone who has issues and then merge. For instance, @Mederim

**Comment by Mederim** [comment]
I see now, yeah just rebase, i will fix and make pull

**Comment by jedahan** [comment]
Opening a new PR that just adds the linter

**Pull request closed without merging**
