### PR TITLE
most: new package at 5.1.0 (as well as a fix for last's pull commit message)

### PR DESCRIPTION
**Pull request by AndreiSva**
This pull request adds the most pager, as well as a fix for a silly commit message naming inconsistency I made in the s-lang request and didn't notice until after it was merged. (although I'm not quite sure this is the proper way to fix such mistake; if you could revert the other pull request and I will amend the commit there, that would be much cleaner.)

## Description of package
Most is a featureful pager for Windows and Unix like operating systems. It's built using the slang programming language. It has out of the box features like syntax highlighting, horizontal scrolling, theming, and custom keybinding support.

## Installed manifest of package

```
/var/db/kiss/installed/most/version
/var/db/kiss/installed/most/sources
/var/db/kiss/installed/most/manifest
/var/db/kiss/installed/most/depends
/var/db/kiss/installed/most/checksums
/var/db/kiss/installed/most/build
/var/db/kiss/installed/most/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/local/share/man/man1/most.1
/usr/local/share/man/man1/
/usr/local/share/man/
/usr/local/share/doc/most/most.txt
/usr/local/share/doc/most/most.rc
/usr/local/share/doc/most/most-fun.txt
/usr/local/share/doc/most/lesskeys.rc
/usr/local/share/doc/most/changes.txt
/usr/local/share/doc/most/README
/usr/local/share/doc/most/
/usr/local/share/doc/
/usr/local/share/
/usr/local/bin/most
/usr/local/bin/
/usr/local/
/usr/
```

## New package

- [X] Latest upstream version.
- [X] I agree to maintain this package.
- [X] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
How did I not notice the commit message...

It's fine, don't worry about it. 

However, either your manifest is bad, or `most`'s configure script is very not-good.

**Comment by AndreiSva** [comment]
Tested the package in a sterile kiss chroot and got the same manifest... What kind of problem is there with `most`'s configure script?

**Comment by dilyn-corner** [comment]
There would be something wrong with it if that manifest were correct because it doesn't actually respect --prefix. 

The manifest should look something like this:
```
/var/db/kiss/installed/most/version
/var/db/kiss/installed/most/sources
/var/db/kiss/installed/most/manifest
/var/db/kiss/installed/most/depends
/var/db/kiss/installed/most/checksums
/var/db/kiss/installed/most/build
/var/db/kiss/installed/most/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/most.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/doc/most/most.txt
/usr/share/doc/most/most.rc
/usr/share/doc/most/most-fun.txt
/usr/share/doc/most/lesskeys.rc
/usr/share/doc/most/changes.txt
/usr/share/doc/most/README
/usr/share/doc/most/
/usr/share/doc/
/usr/share/
/usr/bin/most
/usr/bin/
/usr/
```

And it does :) 

So just drop those `slang` commits and lgtm

**Comment by AndreiSva** [comment]
Alright, Sorry again for the commit message 😅.

**Pull request merged**
