### PR TITLE
mediainfo: bumped to 21.09

### PR DESCRIPTION
**Pull request by Vouivre**
## Installed manifest of package

(`kiss manifest <pkg>`)

```
/var/db/kiss/installed/mediainfo/version
/var/db/kiss/installed/mediainfo/sources
/var/db/kiss/installed/mediainfo/manifest
/var/db/kiss/installed/mediainfo/depends
/var/db/kiss/installed/mediainfo/checksums
/var/db/kiss/installed/mediainfo/build
/var/db/kiss/installed/mediainfo/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/bin/mediainfo
/usr/bin/
/usr/
```

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
Close by #729 ?

**Comment by dilyn-corner** [comment]
jkjk. 

Why are these split?

**Comment by Vouivre** [comment]
> Close by #728 ?

Not sure I understand. With the patch I was able to update `libmediainfo`. So with https://github.com/kiss-community/community/pull/728 this PR can also be closed. So if you meant "Closed", the answer is yes.

**Comment by dilyn-corner** [comment]
I mean that `libmediainfo` provides the dev files and `mediainfo` is providing just the binary - I initially misread this PR and thought it was just a duplicate of #728, but this is actually a split package. I was wondering if this was intentional, and if so what the reasoning behind it was. KISS does not split packages without good reason.

**Comment by Vouivre** [comment]
That's right. There is a reason, probably not a good one. When I created this package I took some inspiration from
other distributions, like crux, in which this split exists. I can have a look to get all in one package. In that case perhaps we can also get rid of `libzen`. Ok for you ?
`Mediainfo` is also released as a all in one package, so it should not be difficult.

**Pull request merged**
