### PR TITLE
[ungoogled]chromium: 92.0.4515.107

### PR DESCRIPTION
**Pull request by git-bruh**

### CODE REVIEW

**Comment by git-bruh** [comment]
There is a glibc-ism in 'base/files/scoped_file_linux.cc' (Introduced in https://github.com/chromium/chromium/commit/046ecadf3161329c379ee6d54280ed192e5559df#diff-e0158eaa3c175642fe7fa42c2b6eaee23599d3330e3eeea08de84d95c41915f0R85) that I'm not sure how to solve, it works on glibc since close() is declared as a weak alias to __close (https://github.com/bminor/glibc/blob/master/io/close.c#L37), so you can make a wrapper for it. It's 'fixed' by a simple ifdef, but I'm not confident that it doesn't have security implications since the ifdef will remove the check performed (that crashses the whole browser if false)

**Comment by git-bruh** [comment]
Also seems to require a ulimit of above 4096 with this update, don't know if something went seriously wrong in my build or they just made chromium way fatter

**Comment by dilyn-corner** [comment]
As has been discussed on IRC, I think we'd have to bring this up with Rich -- close() for musl is essentially just stubbed, and there seems to have not been much in the way of movement to change that. The importance of actually fleshing this out is... lost on me, and I "trust" Alpine to make sane choices (as much as I can trust anyone to do the right thing when I don't know them or what they're doing...). 

For what it's worth, I did (what I think is roughly identical to) what Alpine has done [here](https://git.alpinelinux.org/aports/tree/community/chromium/scoped-file.patch), and haven't experienced any issues thus far with `chromium` in the last 24 hours. 
Alpine's choice is probably 'safer' than just ifdef'ing out the whole block, so I'd rather we use their patch I think. But without any movement from musl on this, or somehow convincing Chromium devs to do something different, we don't have much choice.

**Comment by git-bruh** [comment]
Imported the relevant patches from alpine (others were just related to unit tests), not sure if musl-quiche-arena-size.patch is really needed but i added it anyway.
Build still fails with '/usr/bin/ld: obj/third_party/blink/renderer/core/libblink_core.a: error adding symbols: malformed archive' unless i raise ulimit way above 4096. :/

**Comment by git-bruh** [comment]
Bizzarely it works with a _lower_ ulimit of 2048!

**Comment by dilyn-corner** [comment]
I assume this is now all set and builds just fine?

**Comment by git-bruh** [comment]
Sorry i had logged into shithub to comment but forgot to remark as draft.

Everything is fine except for the weird ulimit issue. No idea at all what's causing it :confused:

**Comment by git-bruh** [comment]
Issue is fixed in binutils, a higher ulimit isn't even required now but still keeping it there for users of alternative linkers

**Pull request merged**
