### PR TITLE
json-glib: new package at 1.6.6

### PR DESCRIPTION
**Pull request by Mederim**
## Description of package
JSON library built on GLib

## Installed manifest of package

```
/var/db/kiss/installed/json-glib/version
/var/db/kiss/installed/json-glib/sources
/var/db/kiss/installed/json-glib/manifest
/var/db/kiss/installed/json-glib/depends
/var/db/kiss/installed/json-glib/checksums
/var/db/kiss/installed/json-glib/build
/var/db/kiss/installed/json-glib/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/installed-tests/json-glib-1.0/serialize-simple.test
/usr/share/installed-tests/json-glib-1.0/serialize-full.test
/usr/share/installed-tests/json-glib-1.0/serialize-complex.test
/usr/share/installed-tests/json-glib-1.0/reader.test
/usr/share/installed-tests/json-glib-1.0/path.test
/usr/share/installed-tests/json-glib-1.0/parser.test
/usr/share/installed-tests/json-glib-1.0/object.test
/usr/share/installed-tests/json-glib-1.0/node.test
/usr/share/installed-tests/json-glib-1.0/invalid.test
/usr/share/installed-tests/json-glib-1.0/gvariant.test
/usr/share/installed-tests/json-glib-1.0/generator.test
/usr/share/installed-tests/json-glib-1.0/builder.test
/usr/share/installed-tests/json-glib-1.0/boxed.test
/usr/share/installed-tests/json-glib-1.0/array.test
/usr/share/installed-tests/json-glib-1.0/
/usr/share/installed-tests/
/usr/share/gir-1.0/Json-1.0.gir
/usr/share/gir-1.0/
/usr/share/
/usr/libexec/installed-tests/json-glib-1.0/stream-load.json
/usr/libexec/installed-tests/json-glib-1.0/skip-bom.json
/usr/libexec/installed-tests/json-glib-1.0/serialize-simple
/usr/libexec/installed-tests/json-glib-1.0/serialize-full
/usr/libexec/installed-tests/json-glib-1.0/serialize-complex
/usr/libexec/installed-tests/json-glib-1.0/reader
/usr/libexec/installed-tests/json-glib-1.0/path
/usr/libexec/installed-tests/json-glib-1.0/parser
/usr/libexec/installed-tests/json-glib-1.0/object
/usr/libexec/installed-tests/json-glib-1.0/node
/usr/libexec/installed-tests/json-glib-1.0/invalid.json
/usr/libexec/installed-tests/json-glib-1.0/invalid
/usr/libexec/installed-tests/json-glib-1.0/gvariant
/usr/libexec/installed-tests/json-glib-1.0/generator
/usr/libexec/installed-tests/json-glib-1.0/builder
/usr/libexec/installed-tests/json-glib-1.0/boxed
/usr/libexec/installed-tests/json-glib-1.0/array
/usr/libexec/installed-tests/json-glib-1.0/
/usr/libexec/installed-tests/
/usr/libexec/
/usr/lib/pkgconfig/json-glib-1.0.pc
/usr/lib/pkgconfig/
/usr/lib/libjson-glib-1.0.so.0.600.6
/usr/lib/libjson-glib-1.0.so.0
/usr/lib/libjson-glib-1.0.so
/usr/lib/girepository-1.0/Json-1.0.typelib
/usr/lib/girepository-1.0/
/usr/lib/
/usr/include/json-glib-1.0/json-glib/json-version.h
/usr/include/json-glib-1.0/json-glib/json-version-macros.h
/usr/include/json-glib-1.0/json-glib/json-utils.h
/usr/include/json-glib-1.0/json-glib/json-types.h
/usr/include/json-glib-1.0/json-glib/json-reader.h
/usr/include/json-glib-1.0/json-glib/json-path.h
/usr/include/json-glib-1.0/json-glib/json-parser.h
/usr/include/json-glib-1.0/json-glib/json-gvariant.h
/usr/include/json-glib-1.0/json-glib/json-gobject.h
/usr/include/json-glib-1.0/json-glib/json-glib.h
/usr/include/json-glib-1.0/json-glib/json-generator.h
/usr/include/json-glib-1.0/json-glib/json-enum-types.h
/usr/include/json-glib-1.0/json-glib/json-builder.h
/usr/include/json-glib-1.0/json-glib/
/usr/include/json-glib-1.0/
/usr/include/
/usr/bin/json-glib-validate
/usr/bin/json-glib-format
/usr/bin/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

### CODE REVIEW

**Comment by git-bruh** [comment]
The gobject-introspection package doesn't exist and json-glib can be built without it: https://github.com/kisslinux/repo/commit/92bc708f77692675cd9844f7cf8ab756488f014b#diff-75f7a574e740954a1ed24464c0cf25c7ee758e8207681c1d37e9e3bd2efac54e

**Comment by Mederim** [comment]
> The gobject-introspection package doesn't exist and json-glib can be built without it: [kisslinux/repo@92bc708#diff-75f7a574e740954a1ed24464c0cf25c7ee758e8207681c1d37e9e3bd2efac54e](https://github.com/kisslinux/repo/commit/92bc708f77692675cd9844f7cf8ab756488f014b#diff-75f7a574e740954a1ed24464c0cf25c7ee758e8207681c1d37e9e3bd2efac54e)

Yeah i know and already packaged it, will pull when json-glib be accepted.

**Comment by git-bruh** [comment]
without, since everything is built with introspection disabled

**Comment by Mederim** [comment]
Okay, will fix it.

**Comment by dilyn-corner** [comment]
Are there actually any packages that require this? There's a reason Dylan stopped bundling it with `glib`...

**Comment by Mederim** [comment]
Will be if i can finish the gimp package otherwise is just a option to someone who need

**Comment by git-bruh** [comment]
`python` isn't a make dep

**Comment by Mederim** [comment]
Fixed

**Comment by dilyn-corner** [comment]
I think we may have discussed this in IRC, but @eudaldgr has a copy of GIMP here https://github.com/eudaldgr/kiss-garbage/tree/master/gfx/gimp which might help you in your endeavors!

**Pull request merged**
