### PR TITLE
ntfs-3g: bump to 2021.8.22

### PR DESCRIPTION
**Pull request by FriendlyNeighborhoodShane**
Also adopt pkg

---

## Description of package

FUSE tool to mount NTFS filesystems.

## Installed manifest of package

(`kiss manifest <pkg>`)

```
/var/db/kiss/installed/ntfs-3g/version
/var/db/kiss/installed/ntfs-3g/sources
/var/db/kiss/installed/ntfs-3g/manifest
/var/db/kiss/installed/ntfs-3g/depends
/var/db/kiss/installed/ntfs-3g/checksums
/var/db/kiss/installed/ntfs-3g/build
/var/db/kiss/installed/ntfs-3g/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/ntfswipe.8
/usr/share/man/man8/ntfsusermap.8
/usr/share/man/man8/ntfsundelete.8
/usr/share/man/man8/ntfstruncate.8
/usr/share/man/man8/ntfssecaudit.8
/usr/share/man/man8/ntfsresize.8
/usr/share/man/man8/ntfsrecover.8
/usr/share/man/man8/ntfsprogs.8
/usr/share/man/man8/ntfsls.8
/usr/share/man/man8/ntfslabel.8
/usr/share/man/man8/ntfsinfo.8
/usr/share/man/man8/ntfsfix.8
/usr/share/man/man8/ntfsfallocate.8
/usr/share/man/man8/ntfsdecrypt.8
/usr/share/man/man8/ntfscp.8
/usr/share/man/man8/ntfscmp.8
/usr/share/man/man8/ntfscluster.8
/usr/share/man/man8/ntfsclone.8
/usr/share/man/man8/ntfscat.8
/usr/share/man/man8/ntfs-3g.probe.8
/usr/share/man/man8/ntfs-3g.8
/usr/share/man/man8/mount.ntfs-3g.8
/usr/share/man/man8/mount.lowntfs-3g.8
/usr/share/man/man8/mkntfs.8
/usr/share/man/man8/mkfs.ntfs.8
/usr/share/man/man8/
/usr/share/man/
/usr/share/doc/ntfs-3g/README
/usr/share/doc/ntfs-3g/
/usr/share/doc/
/usr/share/
/usr/sbin/ntfsundelete
/usr/sbin/ntfsresize
/usr/sbin/ntfslabel
/usr/sbin/ntfscp
/usr/sbin/ntfsclone
/usr/sbin/mkntfs
/usr/sbin/mkfs.ntfs
/usr/sbin/
/usr/lib/pkgconfig/libntfs-3g.pc
/usr/lib/pkgconfig/
/usr/lib/ntfs-3g/
/usr/lib/libntfs-3g.so.89.0.0
/usr/lib/libntfs-3g.so.89
/usr/lib/libntfs-3g.so
/usr/lib/libntfs-3g.a
/usr/lib/
/usr/include/ntfs-3g/xattrs.h
/usr/include/ntfs-3g/volume.h
/usr/include/ntfs-3g/unistr.h
/usr/include/ntfs-3g/types.h
/usr/include/ntfs-3g/support.h
/usr/include/ntfs-3g/security.h
/usr/include/ntfs-3g/runlist.h
/usr/include/ntfs-3g/reparse.h
/usr/include/ntfs-3g/realpath.h
/usr/include/ntfs-3g/plugin.h
/usr/include/ntfs-3g/param.h
/usr/include/ntfs-3g/object_id.h
/usr/include/ntfs-3g/ntfstime.h
/usr/include/ntfs-3g/mst.h
/usr/include/ntfs-3g/misc.h
/usr/include/ntfs-3g/mft.h
/usr/include/ntfs-3g/logging.h
/usr/include/ntfs-3g/logfile.h
/usr/include/ntfs-3g/lcnalloc.h
/usr/include/ntfs-3g/layout.h
/usr/include/ntfs-3g/ioctl.h
/usr/include/ntfs-3g/inode.h
/usr/include/ntfs-3g/index.h
/usr/include/ntfs-3g/endians.h
/usr/include/ntfs-3g/efs.h
/usr/include/ntfs-3g/ea.h
/usr/include/ntfs-3g/dir.h
/usr/include/ntfs-3g/device_io.h
/usr/include/ntfs-3g/device.h
/usr/include/ntfs-3g/debug.h
/usr/include/ntfs-3g/compress.h
/usr/include/ntfs-3g/compat.h
/usr/include/ntfs-3g/collate.h
/usr/include/ntfs-3g/cache.h
/usr/include/ntfs-3g/bootsect.h
/usr/include/ntfs-3g/bitmap.h
/usr/include/ntfs-3g/attrlist.h
/usr/include/ntfs-3g/attrib.h
/usr/include/ntfs-3g/acls.h
/usr/include/ntfs-3g/
/usr/include/
/usr/bin/ntfsls
/usr/bin/ntfsinfo
/usr/bin/ntfsfix
/usr/bin/ntfscmp
/usr/bin/ntfscluster
/usr/bin/ntfscat
/usr/bin/ntfs-3g.probe
/usr/bin/
/usr/
/sbin/mount.ntfs-3g
/sbin/mount.lowntfs-3g
/sbin/
/bin/ntfs-3g
/bin/lowntfs-3g
/bin/
```

## New package

- [X] Latest upstream version.
- [X] I agree to maintain this package.
- [X] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

## Existing package

- [ ] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
```
/usr/sbin/ntfsundelete
/usr/sbin/ntfsresize
/usr/sbin/ntfslabel
/usr/sbin/ntfscp
/usr/sbin/ntfsclone
/usr/sbin/mkntfs
/usr/sbin/mkfs.ntfs
/usr/sbin/
-- snip --
/sbin/mount.ntfs-3g
/sbin/mount.lowntfs-3g
/sbin/
/bin/ntfs-3g
/bin/lowntfs-3g
/bin/
```

Something terrible has happened! 
Try setting `--sbindir=/usr/bin` in the configure step; though you might to have do what we do for `util-linux` (which also doesn't cooperate) 
# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

**Comment by FriendlyNeighborhoodShane** [comment]
> Something terrible has happened!

I noticed too — but I checked, and the last version also built like this, with those few delinquents outside of `/usr`. So I just decided to ignore it.

> Try setting `--sbindir=/usr/bin` in the configure step; though you might to have do what we do for `util-linux` (which also doesn't cooperate)
> https://github.com/kisslinux/repo/blob/409439279a348c6a0710c9a475ebe534a037d137/extra/util-linux/build#L21-L23

Thanks, will try to fix.

**Comment by dilyn-corner** [comment]
Yeah, there are a couple packages that were merged which violate 'the standards'. In general, it's fine; this is one of those things that maybe doesn't have to be fixed (unlike `libexec`), because `/bin` & `/usr/sbin` -> `/usr/bin`, but it's safest to do so.

**Comment by FriendlyNeighborhoodShane** [comment]
`--sbindir` worked for those in `/usr/sbin`, but the rest still had to be manually handled.

New manifest:

```
/var/db/kiss/installed/ntfs-3g/version
/var/db/kiss/installed/ntfs-3g/sources
/var/db/kiss/installed/ntfs-3g/manifest
/var/db/kiss/installed/ntfs-3g/depends
/var/db/kiss/installed/ntfs-3g/checksums
/var/db/kiss/installed/ntfs-3g/build
/var/db/kiss/installed/ntfs-3g/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/ntfswipe.8
/usr/share/man/man8/ntfsusermap.8
/usr/share/man/man8/ntfsundelete.8
/usr/share/man/man8/ntfstruncate.8
/usr/share/man/man8/ntfssecaudit.8
/usr/share/man/man8/ntfsresize.8
/usr/share/man/man8/ntfsrecover.8
/usr/share/man/man8/ntfsprogs.8
/usr/share/man/man8/ntfsls.8
/usr/share/man/man8/ntfslabel.8
/usr/share/man/man8/ntfsinfo.8
/usr/share/man/man8/ntfsfix.8
/usr/share/man/man8/ntfsfallocate.8
/usr/share/man/man8/ntfsdecrypt.8
/usr/share/man/man8/ntfscp.8
/usr/share/man/man8/ntfscmp.8
/usr/share/man/man8/ntfscluster.8
/usr/share/man/man8/ntfsclone.8
/usr/share/man/man8/ntfscat.8
/usr/share/man/man8/ntfs-3g.probe.8
/usr/share/man/man8/ntfs-3g.8
/usr/share/man/man8/mount.ntfs-3g.8
/usr/share/man/man8/mount.lowntfs-3g.8
/usr/share/man/man8/mkntfs.8
/usr/share/man/man8/mkfs.ntfs.8
/usr/share/man/man8/
/usr/share/man/
/usr/share/doc/ntfs-3g/README
/usr/share/doc/ntfs-3g/
/usr/share/doc/
/usr/share/
/usr/lib/pkgconfig/libntfs-3g.pc
/usr/lib/pkgconfig/
/usr/lib/ntfs-3g/
/usr/lib/libntfs-3g.so.89.0.0
/usr/lib/libntfs-3g.so.89
/usr/lib/libntfs-3g.so
/usr/lib/libntfs-3g.a
/usr/lib/
/usr/include/ntfs-3g/xattrs.h
/usr/include/ntfs-3g/volume.h
/usr/include/ntfs-3g/unistr.h
/usr/include/ntfs-3g/types.h
/usr/include/ntfs-3g/support.h
/usr/include/ntfs-3g/security.h
/usr/include/ntfs-3g/runlist.h
/usr/include/ntfs-3g/reparse.h
/usr/include/ntfs-3g/realpath.h
/usr/include/ntfs-3g/plugin.h
/usr/include/ntfs-3g/param.h
/usr/include/ntfs-3g/object_id.h
/usr/include/ntfs-3g/ntfstime.h
/usr/include/ntfs-3g/mst.h
/usr/include/ntfs-3g/misc.h
/usr/include/ntfs-3g/mft.h
/usr/include/ntfs-3g/logging.h
/usr/include/ntfs-3g/logfile.h
/usr/include/ntfs-3g/lcnalloc.h
/usr/include/ntfs-3g/layout.h
/usr/include/ntfs-3g/ioctl.h
/usr/include/ntfs-3g/inode.h
/usr/include/ntfs-3g/index.h
/usr/include/ntfs-3g/endians.h
/usr/include/ntfs-3g/efs.h
/usr/include/ntfs-3g/ea.h
/usr/include/ntfs-3g/dir.h
/usr/include/ntfs-3g/device_io.h
/usr/include/ntfs-3g/device.h
/usr/include/ntfs-3g/debug.h
/usr/include/ntfs-3g/compress.h
/usr/include/ntfs-3g/compat.h
/usr/include/ntfs-3g/collate.h
/usr/include/ntfs-3g/cache.h
/usr/include/ntfs-3g/bootsect.h
/usr/include/ntfs-3g/bitmap.h
/usr/include/ntfs-3g/attrlist.h
/usr/include/ntfs-3g/attrib.h
/usr/include/ntfs-3g/acls.h
/usr/include/ntfs-3g/
/usr/include/
/usr/bin/ntfsundelete
/usr/bin/ntfsresize
/usr/bin/ntfsls
/usr/bin/ntfslabel
/usr/bin/ntfsinfo
/usr/bin/ntfsfix
/usr/bin/ntfscp
/usr/bin/ntfscmp
/usr/bin/ntfscluster
/usr/bin/ntfsclone
/usr/bin/ntfscat
/usr/bin/ntfs-3g.probe
/usr/bin/ntfs-3g
/usr/bin/mount.ntfs-3g
/usr/bin/mount.lowntfs-3g
/usr/bin/mkntfs
/usr/bin/mkfs.ntfs
/usr/bin/lowntfs-3g
/usr/bin/
/usr/
```

**Pull request merged**
